///////////////////////////////////////////////////////////
//  Barriere.cs
//  Implementation of the Class Barriere
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Barriere {

	private int idBarriere;
	private Bool etat;
	private String type;
	public Parking m_Parking;

	public Barriere(){

	}

	~Barriere(){

	}

}//end Barriere