///////////////////////////////////////////////////////////
//  Conducteur.cs
//  Implementation of the Class Conducteur
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Conducteur {

	private int idConducteur;
	private String immatriculation;

	public Conducteur(){

	}

	~Conducteur(){

	}

}//end Conducteur