

///////////////////////////////////////////////////////////
//  Incident.cs
//  Implementation of the Class Incident
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Incident {

	private int idIncident;
	private String nom;
	private String description;
	public Ticket m_Ticket;
	public Operateur m_Operateur;

	public Incident(){

	}

	~Incident(){

	}

}//end Incident