///////////////////////////////////////////////////////////
//  Operateur.cs
//  Implementation of the Class Operateur
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Operateur {

	private int idOperateur;
	private String nom;
	private String prenom;

	public Operateur(){

	}

	~Operateur(){

	}

}//end Operateur