///////////////////////////////////////////////////////////
//  Paiement.cs
//  Implementation of the Class Paiement
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Paiement {

	private int idPaiement;
	private DateTime dateHeure;
	private float montant;
	private String mode;

	public Paiement(){

	}

	~Paiement(){

	}

}//end Paiement