///////////////////////////////////////////////////////////
//  Parking.cs
//  Implementation of the Class Parking
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Parking {

	private int idParking;
	private int nbPlaces;
	private String adresse;

	public Parking(){

	}

	~Parking(){

	}

}//end Parking