///////////////////////////////////////////////////////////
//  Place.cs
//  Implementation of the Class Place
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Place {

	private int numPlace;
	private Bool etat;
	public Parking m_Parking;

	public Place(){

	}

	~Place(){

	}

}//end Place