///////////////////////////////////////////////////////////
//  Tarification.cs
//  Implementation of the Class Tarification
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Tarification {

	private int id;
	private float tarifHoraire;
	private float dureeGratuite;
	public Parking m_Parking;

	public Tarification(){

	}

	~Tarification(){

	}

}//end Tarification