///////////////////////////////////////////////////////////
//  Ticket.cs
//  Implementation of the Class Ticket
//  Generated by Enterprise Architect
//  Created on:      18-juin-2025 12:31:46
//  Original author: Antho
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ticket {

	private int idTicket;
	private DateTime dateHeureEntree;
	private DateTime dateHeureSortie;
	private float montant;
	private Bool paye;
	public Paiement m_Paiement;
	public Parking m_Parking;
	public Conducteur m_Conducteur;

	public Ticket(){

	}

	~Ticket(){

	}

}//end Ticket